name: Deploy Lambda

on:
  push:
    branches:
      - main   # Triggers on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        if: ${{ hashFiles('requirements.txt') != '' }}
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .

      - name: Zip Lambda code
        run: zip -r function.zip . -x "*.git*" -x "*.vscode*" -x "*.github*"

      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          run: |
            aws lambda update-function-code \
              --function-name myLambdaFunction \
              --zip-file fileb://function.zip

