name: Deploy Lambda

on:
  push:
    branches:
      - main   # Triggers on push to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install dependencies if needed (Python example)
      - name: Install dependencies
        if: exists('requirements.txt')
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -t .

      # Step 3: Zip Lambda function
      - name: Zip Lambda code
        run: zip -r function.zip . -x "*.git*" -x "*.vscode*"

      # Step 4: Deploy to AWS Lambda using secrets
      - name: Deploy to AWS Lambda
        uses: aws-actions/aws-cli-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1       # Change to your Lambda's region
          run: |
            aws lambda update-function-code \
              --function-name lambda_function \
              --zip-file fileb://function.zip
